import type { Metadata } from "next";
import "./globals.css";
import "./assets/colors.css";
import StoreProvider from "./StoreProvider";
import LayoutContent from "./LayoutContent";
import { LiveStreamProvider } from "./context/LiveStreamContext";
import { LanguageProvider } from "./i18n/LanguageProvider";

export const metadata: Metadata = {
  title: "ReelBoost",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="tr">
      <head>
        <link
          href="https://fonts.googleapis.com/css?family=Poppins"
          rel="stylesheet"
        />
      </head>
      <body className="font-poppins">
        <LanguageProvider>
          <StoreProvider>
            <LiveStreamProvider>
              <LayoutContent>{children}</LayoutContent>
            </LiveStreamProvider>
          </StoreProvider>
        </LanguageProvider>
      </body>
    </html>
  );
}
